name: CI
run-name: Continuous Integration for Node.js project via reusable workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  node:
    if: false # Disable direct execution
    uses: recursivezero/action-club/.github/workflows/node-ci.yml
    with:
      node-version: "20"
      run-tests: true
