name: Check PAT Secret
run-name: Verify Token validity and authenticity

# save PAT in repo secrets with name as ISSUE_TOKEN

on: workflow_dispatch

jobs:
  test-pat:
    runs-on: ubuntu-latest
    steps:
      - name: Test if PAT works
        run: |
          curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.ISSUE_TOKEN }}" \
            https://api.github.com/user
