name: Bump Version
run-name: bump version and update changelog

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Run bump-version action
        uses: recursivezero/action-club/.github/actions/bump-version@main
        with:
          node-version: "18"
          enable-bump: "true"
          enable-changelog: "false"   # disables changelog update
