name: Release
run-name: bump version and update changelog

on:
  push:
    branches:
      - main

permissions:
  contents: write # needed to push commits and tags

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed to get tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Bump version
        run: |
          bump="${{ github.event.head_commit.message }}"
          echo "Commit message: $bump"
          if [[ "$bump" == *"#minor"* ]]; then
            npm version minor -m "chore: bump minor version"
          elif [[ "$bump" == *"#major"* ]]; then
            npm version major -m "chore: bump major version"
          else
            npm version patch -m "chore: bump patch version"
          fi

      - name: Update CHANGELOG
        run: |
          latest_tag=$(git describe --tags --abbrev=0 HEAD^ || echo "")
          new_tag=$(git describe --tags --abbrev=0 HEAD)
          changelog_date=$(date +"%a, %b %d %Y")  # or "%Y-%m-%d"
          {
            echo "## [$new_tag] - $changelog_date"
            if [ -n "$latest_tag" ]; then
              git log ${latest_tag}..HEAD --pretty=format:"- %s"
            else
              git log HEAD --pretty=format:"- %s"
            fi
            echo ""
          } >> CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "docs: update changelog for $new_tag" || echo "No changelog update needed"

      - name: Push changes
        run: |
          git push --follow-tags
